# Site setings
name: 'cassiomolin'
description: 'A collection of programming insights by Cassio Mazzochi Molin.'
meta_description: 'A collection of programming insights by Cassio Mazzochi Molin.'
logo: null
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: https://cassiomolin.com
disqus: 'cassiomolin'
cover_image: bc_1.jpg
ga_analytics: UA-69796629-3

# Author
author:
  name: 'Cassio Mazzochi Molin'
  image: 'cassiomolin.jpg'
  greetings: null
  description: |
    Hey! I'm Cassio Mazzochi Molin!<br>
    I'm a software engineer living, working and drinking in Ireland.<br>
    I've been using Java for many years and I still love it.
  bio: |
    Cassio Mazzochi Molin is a software engineer living, working and drinking in Ireland.<br>
    He has been using Java for many years and still loves it.

# Contact form setings
contact:
  description: "Would you like to drop me a line? Suggest me a new post? Or simply say hello? So fill the form below and I will get back to you soon."
  google_script_url: https://script.google.com/macros/s/AKfycbzunPZvyXcwHWULmwejUDULxBviv6NqWcIX6KZAupX_MsySK9rQ/exec
  message_sent: 'Thanks for getting in touch!'
  contact_you_soon: 'I will get back to you soon!'

# Social links
github: 'cassiomolin'
linkedin: 'cassiomolin'
stackoverflow: '1426227'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: CV
    url: /cv/
  - text: Contact
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: pretty

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
