---
title: Insights
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: by cassiomolin
author: Cassio Mazzochi Molin
description: Programming insights by Cassio Molin
baseurl: ''
url: http://cassiomolin.com
lang: en_GB
social:
  name: Cassio Mazzochi Molin
  links:
  - https://www.linkedin.com/in/cassiomolin
  - https://github.com/cassiomolin
  - https://instagram.com/cassiomolin
  - https://stackoverflow.com/u/1426227
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
sass:
  sass_dir: assets/sass
kramdown:
  input: GFM
paginate: 5
paginate_path: "/archive/page-:num/"
permalink: pretty
limitPosts: 12
offsetPosts: 1
