source:
  path: "/Users/cassiomolin/Desktop/starting-my-photography-blog"

target:

  path: "/Users/cassiomolin/Development/cassiomolin.github.io/content/photography/starting-my-photography-blog/images"
  delete-content: true
  skip-if-exists: false

  quality: 75
  max-sizes:
   - 500
   - 800
   - 1500
   - 4000

  # The shorter, the higher the risk of collision
  # 15^5 = 1,048,576 -> Seems good enough for this case
  identifier-length: 5
